### ISSUE TITLE
[Windows] In-game packs manager can not download OXP over HTTPS

### ISSUE THREAD

**Issue by AndSDev** [OoliteProject/oolite#205] opened 2016-08-17 09:18 UTC
Manage Expansion Packs can not download OXP over HTTPS on Windows.
Downloading fails on with message:

> 16:25:19.376 [gnustep]: 2016-08-16 16:25:19.376 oolite[6008] Attempt to use SSL/TLS without support.
> 
> 16:25:19.376 [gnustep]: 2016-08-16 16:25:19.376 oolite[6008] Please reconfigure gnustep-base with GNU TLS.
> 
> 16:25:19.664 [oxz.manager.error]: Downloaded OXZ does not contain a manifest.plist, has been left in D:\Games/Oolite/oolite.app/GNUstep/Library/Caches/org.aegidian.oolite/Oolite-download.oxz

"Oolite-download.oxz" is empty (0 bytes).

Oolite on Mac OS ~~/ Linux (Ubuntu)~~ work fine.

Package with HTTPS: Stashes (Activities).

**Comment by AnotherCommander** [comment] 2016-08-17 09:55
GNUstep on the Windows port is unfortunately not configured for secure connections. The issue you have is a known one, but at the time when the bundled gnustep-base for Windows was built for Oolite, there were no plans for using its socket portion for anything other than the Debug Console. The only way to fix this is rebuild GNUstep from scratch, but this may take a while due to time restrictions and scope of the task (GNUstep must be built specifically for Oolite and the official GNUstep versions for Windows are not sufficient to run it because they do not provide support for native obj-c exceptions).

**Comment by AndSDev** [comment] 2016-08-17 10:13
You must only use GNUstep to download OXP?
Additional library can solve this problem (eg, libcurl).

**Comment by AnotherCommander** [comment] 2016-08-17 12:35
We use GNUstep to maintain portability. Of course, if portability is of no concern, we could go about any other way we can think of in order to achieve the objective. Still, this is by no means a small task and I am not sure that anyone else from the team is working on Windows support. As I do not have the possibility to allocate time for a task of this magnitude at this time, I would appreciate any external help and contribution.

**Comment by KonstantinosSykas** [comment] 2016-08-25 19:37
Problem exists in Oolite for Linux too, for installation packages downloaded from oolite.org. 
A nightly should be available tomorrow to test a solution for Linux 64bit architectures.

Depending on the Linux 64bit test outcome, Linux 32bit and Windows architectures may follow.

**Comment by AnotherCommander** [comment] 2016-08-29 20:15
Two new Windows gnustep-base dlls were just commited, aiming to resolve this problem. Internal tests show that now downloading from https addresses is possible (Stashes.oxp used as example). Please check and confirm; the new dlls will be deployed with tomorrow's nightly build.

PS: This has been an exhausting experience. I would not want to ever have to go through anything like this again. Ever.

**Comment by AndSDev** [comment] 2016-09-12 17:32
Win 7 x64 Pro - work fine (nightly x64 and x84 builds).
Win 10 x64 Corp - work fine (nightly x64 and x84 builds).

Ubuntu 16.04 (I made a mistake when checking) - cannot download.

oolite-trunk-1.85.0.fd5ce0a-dev.linux-x86_64.run

When download Stashes hung "Downloading Stashes: Unknown of Unknown":
```
20:03:07.651 [oxz.manager.debug]: Trying to install index 15
20:03:07.653 [oxz.manager.debug]: Download request received, using https://www.dropbox.com/s/l3iquk5sbqcvymi/oolite.oxp.popsch.Stashes.oxz?dl=1 and downloading to /home/max/GNUstep/Library/Caches/org.aegidian.oolite/Oolite-download.oxz
```

HTTP downloaded normal.

With static HTTPS file (not with redirect as dropbox) return error page "400 Bad request":
```
20:11:54.404 [oxz.manager.debug]: Trying to install index 250
20:11:54.543 [oxz.manager.debug]: Download request received, using https://12009.selcdn.ru/links/oolite/MFDRestoreAfterLoad_0.1.oxz and downloading to /home/max/GNUstep/Library/Caches/org.aegidian.oolite/Oolite-download.oxz
20:11:54.750 [oxz.manager.debug]: Download receiving
20:11:54.750 [oxz.manager.debug]: Downloaded 90 bytes
20:11:54.766 [oxz.manager.debug]: Download complete
20:11:54.788 [oxz.manager.error]: Downloaded OXZ does not contain a manifest.plist, has been left in /home/max/GNUstep/Library/Caches/org.aegidian.oolite/Oolite-download.oxz
```

In Oolite-download.oxz:
```
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</bo...
```

**P.S.** on Ubuntu had to install extra libgcrypt.so.11
**P.P.S.** sorry for the delay in replying. Just returned from a trip.

**Comment by AnotherCommander** [comment] 2016-09-12 18:57
Thanks for the feedback. We will leave this issue open while the Linux issue is being worked on.

**Comment by KonstantinosSykas** [comment] 2016-09-13 07:40
Sorry for the delay in Linux. 
Tried to sort things out during my vacation, a couple of weeks ago, but things got really messy and now I have to start all over.

**Comment by KonstantinosSykas** [comment] 2016-09-14 09:56
A new nightly will be made available at around 10:35am (UTC). 
Tested successfully on Linux Mint 18 "Sarah" Cinnamon vanilla.

However, when tried on a Slax distro, Stashes downloading freezes at the _known_ status  `Unknown of Unknown`  :-(

**Comment by AnotherCommander** [comment] 2016-09-16 07:37
With functionality confirmed on at least three Linux distros, are we ok to go ahead and close this? If so, I'll leave to Konstantinos the pleasure of clicking the Close button on this one :-)

**Comment by KonstantinosSykas** [comment] 2016-09-16 07:47
I will proceed the next couple of days into applying the changes to the 32bit Linux built too.

**Comment by KonstantinosSykas** [comment] 2016-09-23 00:03
Following a thorough search, reverse engineering and experimentation on the matter some new information has come to light.

First of all, the reported successful tests on Fedora 24, openSUSE Leap 42.1 and Linux Mint 18 "Sarah" were false positives based on erroneous Oolite-manifests.plist. This issue was resolved by updating to the latest expansion pack list in each test. Some manual fiddling with the manifests plist was necessary for testing with 12009.seldn.ru

Then, comes GnuTLS and the Trusted Root (C)ertification (A)uthorities store location.
Pop Quiz: https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

As of 8/May/2012, the root CA store location must be configured at compile time. The latest GnuTLS version, compiled for Oolite (i.e. commit #5e73cfb), assumes /etc/ssl/certs as the default root CA store location. If this folder is not implemented and the expansion pack is delivered by an HTTPS url, then Oolite will fail fetching it. In this case try locating the folder where the root CA store is locating for your distro and make a symbolic link /etc/ssl/certs pointing at that directory. I couldn't replicate this case to confirm the validity of my suggestion, though. 

The third issue, seems to be the old... very old gcc suite used. This has not yet been elegantly resolved and it wil still tak time. It involves a decision on the compatibility with old Linux releases.

As already posted in the forum,  a new nightly (i.e. 5e73cfb) is on its way, trying to address most of the SSL/TLS implementations proposed by the multitude of Linux distros currently out there

Please, give it a try and return some feedback.

Tested with updated manifests.plist on Fedora 24, openSUSE Leap 42.1, Linux Mint 18 "Sarah" and Ubuntu16.04/

**Comment by KonstantinosSykas** [comment] 2016-09-26 09:17
As per [latest reports in our board](http://bb.aegidian.org/viewtopic.php?p=251652#p251652), it seems that we have a Pyrrhic winner.
While preparing the Oolite for Linux 32bit libraries, I prefer to keep this open, to leave space for more testing.

**Comment by KonstantinosSykas** [comment] 2017-01-18 22:59
The relevant Oolite for Linux 32bit solution has been published in git and a new nightly (i.e. 1359b59) is on its way. The issue will remain open for a couple of days to leave some room for testing and if no reports dictate otherwise, I will close it this Sunday.

**Closed** 2017-01-22 17:54 UTC
