### ISSUE TITLE
tangent space

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#184] opened 2016-03-28 10:53 UTC
Is there a way to get correct tangent space in Oolite? Most exported models (.obj) contain the necessary data.

**Comment by kanthoney** [comment] 2016-03-29 13:14
I found this in `OOShaderMaterial.h`:

```
enum
{
    /*  ID of vertex attribute used for tangents. A fixed ID is used for
        simplicty.
        NOTE: on Nvidia hardware, attribute 15 is aliased to
        gl_MultiTexCoord7. This is not expected to become a problem.
    */
    kTangentAttributeIndex = 15
};
```

which I guess means the tangent vector is put into attribute location 15.  Does that help?

**Comment by CmdrSvengali** [comment] 2016-03-29 14:03
Thanks kanthoney. But I think it has more to do with the way how Oolite calculates the face tangents. Currently we can do some bump mapping, but no normal mapping (which would be a significant improvement for lighting).

**Comment by AnotherCommander** [comment] 2016-03-29 14:46
I may be missing something here, but Oolite has had support for normal and parallax maps for years now, no? The Materials Test OXP in Tests goes through various shader scenarios in order to ensure that this works.

I guess I am missing something though, so some more detailed input would be appreciated. Olli, which part of the code are you actually referring to?

**Comment by kanthoney** [comment] 2016-03-29 15:07
Oolite will read tangents from the `TANGENTS` section of the vertex data, and if that doesn't exist it calculates them using the texture coordinates as a hint.

**Comment by CmdrSvengali** [comment] 2016-03-29 16:54
Yes, Nikos. It's bump mapping though. I think the related part is in OOMesh.m.

Yes, kanthoney. Oolite looks for TANGENTS, but Wavefront .obj doesn't contain tangent data and the recommended converter, Obj2DatTexNorm.py, writes vertex positions, vertex normals, texture vertices and faces. If I understand it right there is no useful way of storing tangent data in .obj or .dat and only Oolite can generate them.

**Comment by CmdrSvengali** [comment] 2016-03-29 19:47
Maybe a piccie helps to see what I mean.
![oolite-tangent01](https://cloud.githubusercontent.com/assets/1322644/14121364/70cec120-f5f7-11e5-99b7-0024b96a61f4.png)

**Comment by kanthoney** [comment] 2016-03-30 18:22
Are you asking for a modified `Obj2DatTexNorm.py` which calculates tangents the same way Oolite does?

**Comment by CmdrSvengali** [comment] 2016-03-30 23:53
No, kanthoney. It's not so easy to explain for a non-coder and maybe I'm wrong, but the picture shows that something is not really right. I'm asking for Oolite generating tangents which are usable for normal mapping and lighting - if it can be done without performance hit.

**Comment by AnotherCommander** [comment] 2016-03-31 09:45
Olli, I believe you are wrong in your assertion that Oolite does simply bump mapping. The picture may indeed show an issue related to tangent space for specific models, however, the normal mapped models already in existence (mainly Griff's but other creators' too) are proof that actual normal mapping does happen. Also, parallax maps can be used to create texture displacement effects at low angles, where normal mapping would result in seemingly flat textures, as can be demonstrated by the Material Test OXP. Finally, internally generated planet normal maps are true and proper normal maps from what I can see in OOPlanetTextureGenerator.m..

We will need some more detailed information about the model you are trying to create. It could be a bug somewhere in the tangents generation indeed and then there is this comment from Jens in OOMesh.m, around line 1800:
```
/*	This is conceptually broken.
		At the moment, it's calculating one tangent per "input" vertex. It should
		be calculating one tangent per "real" vertex, where a "real" vertex is
		defined as a combination of position, normal, material and texture
		coordinates.
		Currently, we don't have a format with unique "real" vertices.
		This basically means explicit-normal models without explicit tangents
		can't usefully be normal mapped.
		I don't intend to do anything about this pre-MSNR, although it might be
		possible to fix it by moving tangent generation to the same stage as
		smooth-grouped normal generation.
		-- Ahruman 2010-05-22
	*/
```
Maybe this is part of the problem, but I am afraid my knowledge on the subject is not sufficient to attempt any more detailed analysis at the moment.

**Comment by CmdrSvengali** [comment] 2016-03-31 15:21
Okay, okay, Nikos .-)

But it's not only this mesh which shows uncommon tangents. In the meantime I've tried it with dodecs up to torus knots and all of them are getting more or less unexpected results. And yes, could be that the part with Jens comment is the reason. It's way above my head as well though.

Maybe I should try to export+convert without normals and see what happens.

**Comment by kanthoney** [comment] 2016-03-31 15:40
We could do with a really simple model - say a cube with each face a different colour so we can tell which side is which - with a simple normal map, for example all the normals leaning towards the centre of each face.  That might show up a problem better than a noisy normal map on a complex model.

**Comment by CmdrSvengali** [comment] 2016-03-31 18:30
Ok, kanthoney .-) I've mocked up a small test.oxp with cubes using different uv layouts. The underlaying shader shows binormal, normal or tangent (you can select it). If you really need colored stuff, just whistle.
[https://app.box.com/s/ex9e0txz36bk4y8j62wow8r5v82kdj0q](url) (48.5 KB)

**Comment by kanthoney** [comment] 2016-04-01 13:37
I haven't had a chance to look at the cube (thanks for that), but I did have a play during my lunch break with normal debugging enabled.  What's startlingly obvious is that the tangents aren't being normalized.  I've pushed a branch (`issue_184`) in which they are, but haven't had a chance to see what effect that has due to having to go back to work.

During the quick play I had it did look as though the tangents were at least pointing in a sensible direction.  Whether they're pointing in the increasing `u` texture coordinate direction as they should I've not checked yet.

**Comment by AnotherCommander** [comment] 2016-04-01 14:11
Kevin, are you sure you have pushed your latest changes to the branch? github says that master and issue_184 are identical.

**Comment by kanthoney** [comment] 2016-04-01 14:29
Oh yeah, have to commit first...

**Comment by AnotherCommander** [comment] 2016-04-01 15:36
I think you have hit the nail on the head Kevin. It already looks better in-game (and I don't think it's placebo effect talking here; the cube oxp looks much more reasonable now, while it was just random changing colors before). Olli, do you require an executable for testing with the mountain model?

**Comment by kanthoney** [comment] 2016-04-01 20:04
I think there's another issue.  Here's the cube with the debug normals, with tangents in yellow, normals in blue and binormals in green:

![tangents](https://cloud.githubusercontent.com/assets/5890866/14218144/5022b472-f84a-11e5-826e-96602c738d19.png)

The tangents in the middle of the faces are all nicely lined up straight as you'd expect, but the tangents on the front edge are going off at an angle.  What's happening there is that on the left face the `u` texture coordinate is running up the face while on the right face it's running from right to left.  The tangent is supposed to be in the `u` direction, but if the vertex is on the boundary of two different regions of texture then it ends up as an average.  What should probably happen is that the model converter should split the vertex into two copies with an appropriate tangent for each (which I think is doable, it already splits a vertex if there are two different normals for it).

**Comment by kanthoney** [comment] 2016-04-01 20:28
That looks more like it:

![tangents1](https://cloud.githubusercontent.com/assets/5890866/14219091/2fd8a536-f850-11e5-89af-c5820c8b4af1.png)

Produced using this version of the object conversion utility:
[Obj2DatTexNorm.py.zip](https://github.com/OoliteProject/oolite/files/200293/Obj2DatTexNorm.py.zip)

**Comment by kanthoney** [comment] 2016-04-01 20:43
Pushed a branch `issue_184` with the modified tool to the mesh converters repo.

**Comment by CmdrSvengali** [comment] 2016-04-02 00:11
Wow. That looks great, kanthoney! I didn't have a chance to run it yet, cause I'm still on this damn production, but I'll be back on Sunday.-)

**Comment by AnotherCommander** [comment] 2016-04-02 08:29
32-bit test executable for Windows uploaded here in case of need: https://drive.google.com/file/d/0BwG6R5Qjd1f2MklqT0g4TmdoY3c/view?usp=sharing

I guess in the meantime the OOMesh.m fix can already be imported to master? Also, do we need to consider re-creating all dat models in core Oolite with the updated conversion tool? That might imply quite a bit of work.

**Comment by kanthoney** [comment] 2016-04-02 08:32
Still doesn't look quite there. Some of those tangents aren't at right angles to the normal. They are at right angles to the face normal, but not the vertex one which is what we want.

**Comment by kanthoney** [comment] 2016-04-02 10:44
Thinking about it, it might not be a real world problem.  It arises when you've got a smooth surface join over a discontinuous texture join.  We've got a few of those in the cube because it's a hastily thrown up test sample, but in an actual model you'd probably want your smooth surfaces to have equally smooth texture coordinates anyway.

**Comment by kanthoney** [comment] 2016-04-02 11:29
This (using the latest issue_184 build) looks messier but I think it's more correct.  Everything that should be at right angles is.

![tangents2](https://cloud.githubusercontent.com/assets/5890866/14225999/2aabd276-f8ce-11e5-8976-f1882bee072e.png)

**Comment by AnotherCommander** [comment] 2016-04-02 14:26
32-bit Windows executable containing latest changes, uploaded for testing purposes: https://drive.google.com/file/d/0BwG6R5Qjd1f2ZTRMZVdzLU5pU1E/view?usp=sharing

**Comment by AnotherCommander** [comment] 2016-04-03 16:44
Regarding the model files we have in core, do we want to consider re-creating them from obj? Or maybe we can get away with it - for now - since we don't do normal mapping in core?

Griff has been kind enough to send me some objs for the core shipset, but unfortunately there are still things like asteroids and stations missing and trying to collect this data could be harder than one may think.

**Comment by CmdrSvengali** [comment] 2016-04-03 17:11
Great, Kevin - looks pretty much as expected now on the test mesh. And it also shows what you've said about the seams. Quite a few modelling/sculpting tools will generate these joints on their own though - without a way to influence their creation. I'll export the test mesh without texture coordinates and unwrap it in another tool to see what can be done.

Thanks a lot for the test build, Nikos. Highly appreciated.

**Comment by kanthoney** [comment] 2016-04-03 17:31
I _think_ we'd get away with it on the core ships.  Most of the seams in the ships are sharp angles rather than smooth seams, and I don't think the problem would occur in that situation.  The asteroids have smooths joins but the texture coordinates should be smooth across those joins, so I don't think there'd be a problem there, either.  But, ulitmately, the only way to be absolutely sure is to recreate them and see.

**Comment by CmdrSvengali** [comment] 2016-04-04 11:02
If you need a hand or two let me know.

**Comment by AnotherCommander** [comment] 2016-04-04 11:42
Regardless of whether we recreate models or not at a later stage, are there any objections with merging the fixes of the #184 branch with master? The issue can still remain open until we have confirmed that even after potential re-conversion of models everything stil looks OK, but it looks to me that those fixes should really be in there.

**Comment by kanthoney** [comment] 2016-04-04 18:37
I've just added an option --no-texture-split to the converter tool which reverts to the old behaviour (just in case that's useful to somebody, or if there's an unforseen problem) and pushed that to the mesh converters repo, issue_184 branch.  When I get confirmation that it's doing the right thing on a real world model I'll merge with master.

**Comment by AnotherCommander** [comment] 2016-04-05 12:33
For anyone interested, I have uploaded the obj and mtl model files I received from Griff here:
https://drive.google.com/file/d/0BwG6R5Qjd1f2djJfZkdIclZxaUk/view?usp=sharing
A couple of comments regarding this set:
- The asteroid, boulder and splinter files are missing. I will add them once I receive them from Griff.
- The Ico station source files used in Oolite are no longer available from what it looks like. I received the files for the Ico present in Griff's normal mapped ships set though. This station has slightly different UV layout compared to the standard one, so two textures that need to go with the model are also included in the zip. These are the only textures that are inlcuded; the rest for all models should be the ones from the standard Resources/Textures folder.

If all works out ok, we could commit these files to the oolite-assets repository for archival reasons.

**Comment by CmdrSvengali** [comment] 2016-04-08 13:53
Kevin, looks great now!
![tangents_ok](https://cloud.githubusercontent.com/assets/1322644/14385574/824ea56c-fda1-11e5-9bda-86021b5085a1.jpg)

**Comment by kanthoney** [comment] 2016-04-08 14:24
Wow!  That's a pretty good test!

**Comment by AnotherCommander** [comment] 2016-04-09 12:48
Indeed very good.

All the model source files provided by Griff, including the ones that were missing earlier, have been commited to the oolite-assets repository. Many thanks to Griff for his help with this.

I test-converted the Boa and the Icosahedron and to me it looks that the new Obj2DatTexNorm.py works just fine and the models seem OK from what I could see. Some additional testing would be more than welcome.

**Comment by AnotherCommander** [comment] 2016-11-27 14:46
Kevin's new Obj2DatTexNorm.py has been imported in the master branch of oolite-mesh-converters with commit d5156dc.

**Comment by kanthoney** [comment] 2017-03-14 16:58
Any objections before I close this?

**Comment by AnotherCommander** [comment] 2017-03-14 17:47
I'd say we can close this, but just keep in mind that the obj models we have now have not been run through this new converter. Maybe that's something .we may want to consider in case of any reports related to core models.

**Closed** 2017-03-14 17:57 UTC
