### ISSUE TITLE
Jumpdrive not disabled after ship dies

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#240] opened 2017-07-08 16:28 UTC
If one dies while the jumpdrive is on (e.g. by colliding head on with an asteroid), the camera on the game over screen keeps flying away at the same speed as the jumpdrive.

**Comment by AnotherCommander** [comment] 2017-07-08 19:07
Confirmed, but I would like to call it a feature because it looks awesome.

**Comment by gilbertohasnofb** [comment] 2017-07-08 23:26
:smile: :+1: in that case feel free to close this!

**Comment by AnotherCommander** [comment] 2017-07-09 13:01
Well, this report helped squashing another bug (see commit 42fc5de) so it was very useful indeed.

Closing it with a "won't fix" resolution due to awesomeness overflow, however,, here is the patch against 42fc5de that removes the stars warp effect, for reference and in case we change our mind in the future:
```
diff --git a/src/Core/Entities/PlayerEntity.m b/src/Core/Entities/PlayerEntity.m
index d7317f8..44faf70 100644
--- a/src/Core/Entities/PlayerEntity.m
+++ b/src/Core/Entities/PlayerEntity.m
@@ -6762,6 +6762,8 @@ NSComparisonResult marketSorterByMassUnit(id a, id b, void *market);
 	
 	energy = 0.0f;
 	afterburner_engaged = NO;
+	// uncomment below to disable the stars warp effect when dying in torus speeds
+	//travelling_at_hyperspeed = NO;
 	[self disengageAutopilot];
 
 	[UNIVERSE setDisplayText:NO];
```

**Closed** 2017-07-09 13:01 UTC
