### ISSUE TITLE
Strange happenings in Witchspace (ejecting and witchspacing . .)

### ISSUE THREAD

**Issue by CottonEaster** [OoliteProject/oolite#286] opened 2018-02-05 19:30 UTC
I was in witchspace, and I jettisoned - shortly after engaging the witchdrive. Result: I saw my ship drift off, for (1) longer than usual - for ages. Then, when (because?) I pressed a key, (2) I ended up in the main station of my target system. It's unclear that either 1 or 2 should happen.

Oolite 1.86 (x86-64 test release) under Windows 6.2.9200  64-bit 
Relevant OXPS: InterStellar Tweaks (which I don't think could cause 1 or 2, though it does have escape-pod code).
Clues in the main log: none that I can see.

**Comment by AnotherCommander** [comment] 2018-02-06 06:23
Can this be reproduced with the latest trunk? Please give it a try without any OXPs (it should also report the correct Windows version; 1.86 reports Windows 8 (6.2.9200) even when you are on a later version of the OS and that is fixed in trunk).

I tried reproducing the problem with a minimal OXP set and could not trigger it. I tried normal space and witchspace and also tried ejecting immediately after hyperspace countdown start and also when it was close to 0. In the witchspace scenarios, the behavior of the game was to show the player ship drifting away, followed by the Game Over message. This may indicate OXP interference in your case.

**Comment by CottonEaster** [comment] 2018-02-06 15:28
Thanks for testing. It's only happened to me once. I'll do further testing myself if and when I get time. I am indeed using Windows 8 (not Windows 10).

**Comment by AnotherCommander** [comment] 2018-05-09 06:52
Are there any further updates on this? Considering closing with the "cannot reproduce" resolution.

**Comment by CottonEaster** [comment] 2018-05-09 08:33
I haven't seen the behaviour in a while, perhaps because I haven't played Oolite in a while (!). Perhaps the close can be closed and re-opened if and when anyone else encounters the problem.

**Comment by AnotherCommander** [comment] 2018-05-09 08:42
OK thanks, issue is closed since it cannot be reproduced at this time on a clean Oolite install.

**Closed by AnotherCommander** 2018-05-09 08:42 UTC
