### ISSUE TITLE
No activity (or station) in high tech level systems

### ISSUE THREAD

**Issue by GuamBomb** [OoliteProject/oolite#160] opened 2015-08-16 03:04 UTC
I am using a Mac, and Oolite 1.8.2.  Whenever I enter a high tech level system (about 12+), I find no station, and the spacelane is typically empty.  I once observed a small fleet of GalCop ships flying straight into the planet without adjusting course.  I suspect an OXZ may be responsible, but I haven't identified the culprit.

**Comment by AnotherCommander** [comment] 2015-08-16 07:34
Is this reproducible without any OXPs?

**Comment by GuamBomb** [comment] 2015-08-16 19:55
On a Strict pilot, the problem seems to be gone...  can't confirm exactly for sure without playing a while to get to the systems I observed the issue in.

**Comment by AnotherCommander** [comment] 2015-09-02 10:27
This seems to be an OXP problem. Can we get a confirmation that without OXPs the problem does not occur?

**Comment by GuamBomb** [comment] 2015-09-02 12:50
As I said earlier, the problem does not occur when using a pilot in Strict Mode, which is the same thing as having no OXPs. I also listed the OXPs I had installed in hopes of getting some help to isolate the problematic one

**Comment by AnotherCommander** [comment] 2015-09-02 13:40
OK, then this is not a core game bug and is related to something caused by an OXP. I will close the issue now and suggest that you bring it up for discussion on the forum (at the time of writing this it is down, but hopefully will be back up soon). There, it should be possible to get assistance for locating the problematic OXP; we do not normally track OXP issues on the github tracker.

**Closed by AnotherCommander** 2015-09-02 13:40 UTC
