### ISSUE TITLE
Pitch is not set to neutral

### ISSUE THREAD

**Issue by Springnuts** [OoliteProject/oolite#187] opened 2016-04-17 19:11 UTC
Hi, non-programmer here: the issue is with Ubuntu 15.10 running Oolite version 1.82 installed via the Ubuntu software centre.  When the ship launches there is a little bit of positive pitch set - ie the ship does not fly "straight" if no keys are being pressed but drifts "up".  Roll and Yaw work properly.  Any advice gratefully received. The screenshot says it all - the pitch marker is slightly offset with no key input.  I don't have a joystick attached.

I had a go at uninstalling 1.82 and installing version 1.80 - same issue; actually slightly worse.

![screenshot from 2016-04-17 20-15-51](https://cloud.githubusercontent.com/assets/18517991/14589402/3e4f4864-04d9-11e6-8aa7-67f7de8f29c8.png)

**Comment by Norbylite** [comment] 2016-04-17 19:20
Hi! Your problem sounds similar with this post:
http://bb.aegidian.org/viewtopic.php?f=9&t=15781&hilit=ubuntu+joystick#p210604
Feel free to ask more in the Oolite forum, many helpful people read it.

**Comment by Springnuts** [comment] 2016-04-17 19:42
Huge thanks - that fixed it!

**Comment by AnotherCommander** [comment] 2016-04-17 19:56
Good to know the problem is fixed. Closing this issue.

**Closed by AnotherCommander** 2016-04-17 19:56 UTC
