### ISSUE TITLE
Feature request: override colour of certain hard-coded text

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#235] opened 2017-07-03 00:14 UTC
I would like to make a feature request: to be able to override the colour of any text in the game. This would be particularly useful for the creation of HUD (which is my current case). It would be really great to be able to change the colour of certain text messages which seem to be hard-coded at the moment, such as the "weapons offline" text (always green), or the communication and messages log (always yellow), the FPS counter, etc. Would it be too much trouble adding this feature, perhaps by adding a couple more parameters to the `gui-settings.plist`?

**Comment by AnotherCommander** [comment] 2017-07-03 00:47
Check out commit  4b32237. It contains the implementation for weapons offline and FPS counter texts. Message text color may be a bit trickier though.

**Comment by gilbertohasnofb** [comment] 2017-07-03 08:31
@AnotherCommander many thanks for the fast implementation! I will check it out today. 

> Message text color may be a bit trickier though.

Does that mean that this is not currently a possibility or that implementing this feature for the message and communication log would take more time?

**Comment by AnotherCommander** [comment] 2017-07-03 09:06
Most likely it's that it's going to take longer. I am not planning to look at the comms log though, as it uses different coloors for different senders, will just try the message log color at some point.

**Comment by gilbertohasnofb** [comment] 2017-07-03 09:14
Ok, many thanks once again. I just tested the new nightly and it works like a charm. 

> will just try the message log color at some point.

Should we keep this issue opened until then or is it better to close it already?

And if I may ask one more thing, does the development version always show the message `Development version 1.85.0.6952-170703-4b32237` on the top corner or is it possible to hide it? It's the first time I am using the nightly builds.

**Comment by AnotherCommander** [comment] 2017-07-03 10:14
Thanks for testing. We can keep the issue open until we at least give a try at the message gui color situation.

As for the nightly build watermark, it is not removable by configuration settings. Because nightlies are not an official version, we need to be able to deternine that immediately when someone posts bug reports with screenshots. It also makes easy for people to answer when we ask "which exact develoopment version are you using", without having to dig up logs etc. With all that said, you can remove the watermark by hex editing the executable and replacing the watermark string with spaces. I do it very oftne myself on Windows, but the same principle should work also on Linux.

**Comment by gilbertohasnofb** [comment] 2017-07-03 10:16
@AnotherCommander many, many thanks!

> With all that said, you can remove the watermark by hex editing the executable and replacing the watermark string with spaces.

Great, I will look into that today. I really appreciate all your help.

**Comment by gilbertohasnofb** [comment] 2017-07-03 20:42
@AnotherCommander I just realized that there is one more text which seems to have hard coded color: the zoom ratio of the scanner, which seems to be always red. Would this be an easy fix like the FPS and weapons offline or would it be a tricky one?

**Comment by AnotherCommander** [comment] 2017-07-03 22:40
Actually there is no bug with the scanner zoom, it works as intended and you can change its color already.

Because the dictionary of the scanner zoom indicator contains an "alpha" key, the rgb_color must be entered as an array of three ffloats (r, g, b). If you are entering a 4-element color array there, then it wil not be able to read it. The same happens if you enter a text description for the color, like "yellowColor" or similar; this implies an rgba array. If you want to enter these kinds of descriptions, you must remove the alpha key from the zoom indicator's hud.plist entry.

**Comment by gilbertohasnofb** [comment] 2017-07-03 22:49
> the rgb_color must be entered as an array of three ffloats (r, g, b). If you are entering a 4-element color array there, then it wil not be able to read it. 

That was indeed the problem, removing the fourth float solved the issue. Thanks a lot for all your patience.

**Comment by AnotherCommander** [comment] 2017-07-07 17:52
OK so here is what's happening with tomorrow's nightly (commit 73df6aa or later):

There are two new keys for the message_gui part of the HUD plists. The keys are:
`text_standard_color`: This is the color descriptor for the text that will normally appear in the message gui. Default is yellow.
`text_comms_color`: This is the color descriptor for the text representing incoming comms from other entities. Default is green.

In addition to that, we now have the player.ship read/write properties `messageGuiTextColor` and `messageGuiTextCommsColor` which will allow scripts to change the two colors on the fly.

I think this gives complete freedom to toy around with the messages now and should hopefully address completely this request. Please test and advise in case something goes horribly wrong.

**Comment by AnotherCommander** [comment] 2017-07-08 10:19
The `text_standard_color` message_gui key has been renamed to `text_color` for keeping it consistent between plist and Javascript nomenclatures.

**Comment by gilbertohasnofb** [comment] 2017-07-08 10:45
Great, I will test this all today and report here!

**Comment by gilbertohasnofb** [comment] 2017-07-08 15:17
@AnotherCommander I just tested and this is looking great! Do you also plan to add a standard colour parameter to the `comm_log_gui` or would that be too complicated?

**Comment by AnotherCommander** [comment] 2017-07-08 15:20
I think I'll stop here. The comms log gui uses already three colors and I think trying to control those too will get too complicated. Maybe will look at it again at some time in the future.

**Comment by gilbertohasnofb** [comment] 2017-07-08 15:43
No problems. So I think we can close this issue here -- many, many thanks for all your work! And if you ever get to add those three colour parameters to the `comm_log_gui`, let me know :smile:

**Comment by AnotherCommander** [comment] 2017-07-08 16:15
OK, closing the issue, with a small TODO note for anyone who would like to take it on in the future: apply similar controls to the comm_log_gui colors.

**Closed by AnotherCommander** 2017-07-08 16:15 UTC
