### ISSUE TITLE
Galactic Chart not properly displayed Mac OS X 10.10.3 version 1.82

### ISSUE THREAD

**Issue by HVFrancis** [OoliteProject/oolite#152] opened 2015-05-27 18:23 UTC
On my MacBook Pro (Retina, 15", mid 2014) I am only seeing a partial rendering of the Galactics Chart. The screenshots below come from starting new commander in strict mode. I'm a player, not a dev, so I don't know what other information you'd like from me. But if you tell me what you need and where to find it, I'll be more than happy to look for it.

Howard (aka Aycheff)
![oolite-001](https://cloud.githubusercontent.com/assets/3835354/7844011/86cdcb56-047b-11e5-805d-63cce94b184d.png)
![oolite-003](https://cloud.githubusercontent.com/assets/3835354/7844018/94c51d40-047b-11e5-988d-8f2ee80d3881.png)

**Comment by kanthoney** [comment] 2015-05-27 19:22
This looks like issue #136. The workaround is to open a command prompt and issue the command

    defaults write org.aegidian.oolite issue_136_fix YES

Let us know if that works for you.

**Comment by kanthoney** [comment] 2015-05-27 19:33
It would help if I got the command right:

    defaults write org.aegidian.oolite key -bool YES

**Comment by KonstantinosSykas** [comment] 2015-05-27 20:44
```defaults write org.aegidian.oolite key -bool YES```
will give:
![image](https://cloud.githubusercontent.com/assets/5579524/7846736/2740ca60-04c8-11e5-9d20-84d72a992cc4.png)

```defaults write org.aegidian.oolite issue_136_fix -bool YES```
will give:
![image](https://cloud.githubusercontent.com/assets/5579524/7847043/f9453252-04c9-11e5-9280-cebc278da81f.png)

**Comment by kanthoney** [comment] 2015-05-27 20:47
I'm making a hash of this, aren't I?

To summarize, it's

    defaults write org.aegidian.oolite issue_136_fix -bool YES

**Comment by HVFrancis** [comment] 2015-05-27 20:55
Hi,

I read up on the other issue (sorry for the duplicate) and

 `
defaults write org.aegidian.oolite issue_136_fix 1
`

was what worked for me. The others didn't.

**Comment by kanthoney** [comment] 2015-05-27 20:59
Excellent!

We probably shouldn't have closed the first one until it got fixed properly, so I'll keep this issue open.

**Comment by KonstantinosSykas** [comment] 2015-05-27 21:08
But this syntax is translated as the type of key being a string :astonished:

**Comment by KonstantinosSykas** [comment] 2015-05-28 07:52
@HVFrancis: Please. perform the following:
```
defaults delete org.aegidian.oolite issue_136_fix
defaults write org.aegidian.oolite issue_136_fix -bool YES
```
Start Oolite keeping the `Shift` key pressed.
Check if the issue is resolved. If not, please, post the Latest.log here and revert the latest defaults changes to its previous state:
```
defaults delete org.aegidian.oolite issue_136_fix
defaults write org.aegidian.oolite issue_136_fix 1
```

**Comment by kanthoney** [comment] 2015-05-28 08:13
I think he said he'd got it working, didn't he?

**Comment by KonstantinosSykas** [comment] 2015-05-28 08:30
Yes it worked and I hope that I don't confuse HVFranscis. However, I am thinking about someone that enters this and sees different syntax and approaches. I need to know (this my OCD) if the rational syntax that you suggest (i.e. ```issue_136_fix -bool YES```) works.
I have tested it in a non retina display and this syntax actually changes the way the Chart is rendered, proving that `if (issue_136_fix)` evaluates to `TRUE` doubling the `origin` and `size` properties as per the below:
```
#if OOLITE_MAC_OS_X
	// Fix for issue 136
	if (issue_136_fix)
	{
		clipRect.origin.x *= 2;
		clipRect.origin.y *= 2;
		clipRect.size.width *= 2;
		clipRect.size.height *= 2;
	}
#endif
```
I don't understand why it didn't work for HVFrancis and the syntax `issue_136_fix 1` works with indirect type casting (i.e. string to bool).

**Comment by kanthoney** [comment] 2015-05-28 08:39
Can you try new branch issue_151?  I think that should work on either
retina or non-retina displays without needing the user setting.

On Thu, May 28, 2015 at 9:30 AM, Konstantinos Sykas <
notifications@github.com> wrote:

> Yes it worked and I hope that I don't confuse HVFranscis. However, I am
> thinking about someone that enters this and sees different syntax and
> approaches. I need to know (this my OCD) if the rational syntax that you
> suggest (i.e. issue_136_fix -bool YES) works.
> I have tested it in a non retina display and this syntax actually changes
> the way the Chart is rendered, proving that if (issue_136_fix) evaluates
> to TRUE doubling the origin and size properties as per the below:
>
> #if OOLITE_MAC_OS_X
>     // Fix for issue 136
>     if (issue_136_fix)
>     {
>         clipRect.origin.x *= 2;
>         clipRect.origin.y *= 2;
>         clipRect.size.width *= 2;
>         clipRect.size.height *= 2;
>     }
> #endif
>
> I don't understand why it didn't work for HVFrancis and the syntax issue_136_fix
> 1 works with indirect type casting (i.e. string to bool).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OoliteProject/oolite/issues/152#issuecomment-106231350>
> .
>



-- 
Kevin Anthoney
kevin@kanthoney.co.uk

**Comment by kanthoney** [comment] 2015-05-28 08:42
Make that branch `issue_152`!

**Comment by KonstantinosSykas** [comment] 2015-05-28 09:38
Build fails with
![image](https://cloud.githubusercontent.com/assets/5579524/7857069/7bc2969a-0536-11e5-9368-4c84db2f7c51.png)

**Comment by KonstantinosSykas** [comment] 2015-05-28 10:22
In non retina screen it doesn't show a thing! _(don't have retina screen to test)_
![image](https://cloud.githubusercontent.com/assets/5579524/7857736/8ce87872-053b-11e5-976b-29257f502152.png)

Note 1: Pressing F6/6 keys reverts from Zoomed to Entire Chart view with nothing displayed in it. You only understand the two modes because in the Entire Chart view you can type the name of a planet-system. Otherwise you don't see anything... as in the screenshot

Note 2: In Zoomed view mode, clicking on the emptiness, does return planet-system information on screen.

Note 3: Using `PgUp` and `PgDn` keys never seem to never reach the Entire Chart view.

**Comment by kanthoney** [comment] 2015-05-28 10:23
Just pushed a fix.  Try it again.

On Thu, May 28, 2015 at 11:22 AM, Konstantinos Sykas <
notifications@github.com> wrote:

> In non retina screen it doesn't show a thing! *(don't have retina screen
> to test)*
> [image: image]
> <https://cloud.githubusercontent.com/assets/5579524/7857736/8ce87872-053b-11e5-976b-29257f502152.png>
>
> Note 1: Pressing F6/6 keys reverts from Zoomed to Entire Chart view with
> nothing displayed in it. You only understand the two modes because in the
> Entire Chart view you can type the name of a planet-system. Otherwise you
> don't see anything... as in the screenshot
>
> Note 2: In Zoomed view mode, clicking on the emptiness, does return
> planet-system information on screen.
>
> Note 3: Using PgUp and PgDn keys never seem to never reach the Entire
> Chart view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OoliteProject/oolite/issues/152#issuecomment-106263373>
> .
>



-- 
Kevin Anthoney
kevin@kanthoney.co.uk

**Comment by KonstantinosSykas** [comment] 2015-05-28 11:33
92addcd is OK for non-retina. I will prepare a snapshot build (with watermark) and share the link here just in case someone that cannot build the code, can at least check the Mac OS X binary on a retina display.

**Comment by HVFrancis** [comment] 2015-05-28 14:05
Ok. 
`defaults write org.aegidian.oolite issue_136_fix -bool YES`
worked for me this time. Maybe I typed it wrong the first time.

**Comment by KonstantinosSykas** [comment] 2015-05-28 14:34
@HVFrancis: OK. Now My brain is back in its place. Thank you for your time and effort.

Now for anyone that is willing to test the new approach, offered by Kevin in the [`issue_152 92addcd`](https://github.com/OoliteProject/oolite/tree/issue_152) branch (the one that does not need the presence of the `issue_136_fix` key in the *defaults* file), I have prepared a binary that can be downloaded from
https://drive.google.com/file/d/0B__DrFTwF9vAeGtNcHltNks2ZW8/view?usp=sharing

**Important Note:**  To test that binary you need to ensure that the `issue_136_fix` key is NOT in your *defaults* file, by executing 
`defaults delete org.aegidian.oolite issue_136_fix`
before running the downloaded binary.

**Comment by kanthoney** [comment] 2015-08-04 14:55
So we've got two reports of the test binary on retina Macs: http://aegidian.org/bb/viewtopic.php?f=10&t=17486#p240465 says it works, http://aegidian.org/bb/viewtopic.php?f=10&t=17486#p240478 says it doesn't, with the game playing in the bottom left corner of the screen.  I've pushed a speculative fix to the `issue_152` branch.  Can you dig your Mac out and produce a build, Konstantinos?

**Comment by pleumann** [comment] 2016-03-28 14:16
FWIW I had the same issue with the 1.82 release on a retina 21,5" iMac with OS X 10.11.3. Executing the command line

$ defaults write org.aegidian.oolite issue_136_fix -bool YES

fixed it for me. The galactic chart now looks fine.

**Comment by kanthoney** [comment] 2016-03-29 12:30
Thanks!  I can apply that to trunk, now.  Also applied to the 1.82 maintenance branch.

**Closed by kanthoney** 2016-03-29 12:30 UTC
Labels: duplicate, graphics
